### ISSUE TITLE
在运行run_crf_ner时候 在做evaluate 会出现key error -1的情况

### ISSUE THREAD

**Issue by bestpredicts** [liuyukid/transformers-ner#2]
看了下 应该是在对验证集 推理对时候出现了 -1

**Comment by laleye** [comment]
Hi @bestpredicts 
May you explain more why this error and how did you fix it ?

Thank you

**Comment by Hansyvea** [comment]
这个问题解决了吗？

**Comment by laleye** [comment]
不是從側面  (谷歌翻譯是最好的 )

**Comment by Hansyvea** [comment]
> 
> 
> 不是從側面 (谷歌翻譯是最好的 )

did you find the way to solve this problem? btw I can't get what you were saying in the google translated version...
